### ISSUE TITLE
Django 4 compatibility

### ISSUE THREAD

**Issue by teejayvanslyke** [django-hijack/django-hijack-admin#49]
It appears that django-hijack-admin uses features that have been [deprecated in Django 4](https://docs.djangoproject.com/en/4.0/releases/4.0/#features-removed-in-4-0):

```
ModuleNotFoundError: No module named 'django.conf.urls.defaults'
```

I believe this is a result of importing django-compat, which may not be compatible (or necessary) with Django 4.

**Comment by Mogost** [comment]
Implemented in https://github.com/django-hijack/django-hijack
