### ISSUE TITLE
UserWarning: User is not registered in the default admin. Please integrate hijack into your user admin manually.

### ISSUE THREAD

**Issue by fcoppey** [django-hijack/django-hijack-admin#51]
how to get rid of that?

I do not use hijack in the Django admin but in my custom forms

**Comment by Paaskehare** [comment]
Hi! Just experienced the same issue myself, the problem was that the app my custom User model was defined in, was listed after 'hijack' in INSTALLED_APPS in settings. So the custom user model wasn't included yet when hijack was set up.
